### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by thejasonxie** [PrivaNoteTeam/PrivaNote#18]
## User Story
As a user, I would like to spell check my note information.

## Description
SpellChecker allows users to enable or disable the spell checking feature.

## Acceptance Criteria
- [ ] User should be able to enable or disable the spell check with the toggle switch in the settings page.
- [ ] The spell checking is done based on the selected dictionary language.

**Comment by oliviergoulet5** [comment]
No longer implementing spell check.
