### ISSUE TITLE
Spell Check Language Setting

### ISSUE THREAD

**Issue by thejasonxie** [PrivaNoteTeam/PrivaNote#19]
## User Story
As a user, I would like to set the spell checker to my preferred language.

## Description
Dictionary Language allows users to set the spell checker to their desired language.

## Acceptance Criteria
- [ ] User can choose the languages for the spell checker with the drop menu in the settings page. 
- [ ] The text is parsed out of the .md syntax to prevent spell checking errors.

**Comment by oliviergoulet5** [comment]
No longer implementing Spell Check.
