### ISSUE TITLE
Subscription Plan

### ISSUE THREAD

**Issue by thejasonxie** [PrivaNoteTeam/PrivaNote#47]
## User Story
As a user I want to subscribe to a subscription plan.

## Description
User is provided with a list of subscription plan to choose from.

## Acceptance Criteria
- [ ] Subscription plans have been added to the database
- [ ] Subscription plan are activated after user payment
- [ ] Subscription plan can be cancelled by user

**Comment by oliviergoulet5** [comment]
No longer doing vault subscription.
